-- CnDB
-- Trinitycore 数据库中文支持
-- version 0.1
-- http://code.google.com/p/cndb/

UPDATE `trinity_string` SET `entry` = 1,`content_default` = '您应该选择角色或生物.' WHERE `trinity_string`.`entry` = 1;
UPDATE `trinity_string` SET `entry` = 2,`content_default` = '您应该选择一个生物.' WHERE `trinity_string`.`entry` = 2;
UPDATE `trinity_string` SET `entry` = 3,`content_default` = '|cffff0000[系统消息]: %s|r' WHERE `trinity_string`.`entry` = 3;
UPDATE `trinity_string` SET `entry` = 4,`content_default` = '|cffff0000[游戏广播]: %s|r' WHERE `trinity_string`.`entry` = 4;
UPDATE `trinity_string` SET `entry` = 5,`content_default` = '这里没有此命令的帮助信息' WHERE `trinity_string`.`entry` = 5;
UPDATE `trinity_string` SET `entry` = 6,`content_default` = '这个命令不存在' WHERE `trinity_string`.`entry` = 6;
UPDATE `trinity_string` SET `entry` = 7,`content_default` = '这里没有此类子命令' WHERE `trinity_string`.`entry` = 7;
UPDATE `trinity_string` SET `entry` = 8,`content_default` = '命令 %s 子命令是:%s' WHERE `trinity_string`.`entry` = 8;
UPDATE `trinity_string` SET `entry` = 9,`content_default` = '你可以使用的命令有:' WHERE `trinity_string`.`entry` = 9;
UPDATE `trinity_string` SET `entry` = 10,`content_default` = '命令语法格式错误.' WHERE `trinity_string`.`entry` = 10;
UPDATE `trinity_string` SET `entry` = 11,`content_default` = '你的账号级别是: %i' WHERE `trinity_string`.`entry` = 11;
UPDATE `trinity_string` SET `entry` = 12,`content_default` = '在线人数: %u (最多时: %u) 排队人数: %u (最多时: %u)' WHERE `trinity_string`.`entry` = 12;
UPDATE `trinity_string` SET `entry` = 13,`content_default` = '服务器正常运行时间: %s' WHERE `trinity_string`.`entry` = 13;
UPDATE `trinity_string` SET `entry` = 14,`content_default` = '系统提示：玩家数据保存成功.' WHERE `trinity_string`.`entry` = 14;
UPDATE `trinity_string` SET `entry` = 15,`content_default` = '系统提示：保存所有玩家数据成功.' WHERE `trinity_string`.`entry` = 15;
UPDATE `trinity_string` SET `entry` = 16,`content_default` = '系统提示：在此服务器上有以下在线的G M:' WHERE `trinity_string`.`entry` = 16;
UPDATE `trinity_string` SET `entry` = 17,`content_default` = '系统提示：当前没有G M登录在这台服务器上.' WHERE `trinity_string`.`entry` = 17;
UPDATE `trinity_string` SET `entry` = 18,`content_default` = '系统提示：当处于飞行中时，无法这样做.' WHERE `trinity_string`.`entry` = 18;
UPDATE `trinity_string` SET `entry` = 19,`content_default` = '系统提示：在战场里无法这样做.' WHERE `trinity_string`.`entry` = 19;
UPDATE `trinity_string` SET `entry` = 20,`content_default` = '系统提示：目标在飞行中，你无法这样做.' WHERE `trinity_string`.`entry` = 20;
UPDATE `trinity_string` SET `entry` = 21,`content_default` = '%s 正在飞行中, 命令无效.' WHERE `trinity_string`.`entry` = 21;
UPDATE `trinity_string` SET `entry` = 22,`content_default` = '系统提示：你没有在骑乘状态, 因此你不能卸下骑乘.' WHERE `trinity_string`.`entry` = 22;
UPDATE `trinity_string` SET `entry` = 23,`content_default` = '系统提示：在战斗中无法这样做.' WHERE `trinity_string`.`entry` = 23;
UPDATE `trinity_string` SET `entry` = 24,`content_default` = '系统提示：您最近已经使用过它.' WHERE `trinity_string`.`entry` = 24;
UPDATE `trinity_string` SET `entry` = 25,`content_default` = '系统提示：您的密码不能设置超过16个字符长度(客户极限), 密码没被改变' WHERE `trinity_string`.`entry` = 25;
UPDATE `trinity_string` SET `entry` = 26,`content_default` = '系统提示：密码已经修改.' WHERE `trinity_string`.`entry` = 26;
UPDATE `trinity_string` SET `entry` = 27,`content_default` = '系统提示：新新口令不匹配或旧密码是错误的.' WHERE `trinity_string`.`entry` = 27;
UPDATE `trinity_string` SET `entry` = 28,`content_default` = '系统提示：你的账号现在被锁定.' WHERE `trinity_string`.`entry` = 28;
UPDATE `trinity_string` SET `entry` = 29,`content_default` = '系统提示：你的账号已取消锁定.' WHERE `trinity_string`.`entry` = 29;
UPDATE `trinity_string` SET `entry` = 30,`content_default` = ', rank ' WHERE `trinity_string`.`entry` = 30;
UPDATE `trinity_string` SET `entry` = 31,`content_default` = ' [学会]' WHERE `trinity_string`.`entry` = 31;
UPDATE `trinity_string` SET `entry` = 32,`content_default` = ' [学习]' WHERE `trinity_string`.`entry` = 32;
UPDATE `trinity_string` SET `entry` = 33,`content_default` = ' [被动的]' WHERE `trinity_string`.`entry` = 33;
UPDATE `trinity_string` SET `entry` = 34,`content_default` = ' [天赋]' WHERE `trinity_string`.`entry` = 34;
UPDATE `trinity_string` SET `entry` = 35,`content_default` = ' [激活]' WHERE `trinity_string`.`entry` = 35;
UPDATE `trinity_string` SET `entry` = 36,`content_default` = ' [完成]' WHERE `trinity_string`.`entry` = 36;
UPDATE `trinity_string` SET `entry` = 37,`content_default` = ' (离线)' WHERE `trinity_string`.`entry` = 37;
UPDATE `trinity_string` SET `entry` = 38,`content_default` = '开' WHERE `trinity_string`.`entry` = 38;
UPDATE `trinity_string` SET `entry` = 39,`content_default` = '关' WHERE `trinity_string`.`entry` = 39;
UPDATE `trinity_string` SET `entry` = 40,`content_default` = '你是: %s' WHERE `trinity_string`.`entry` = 40;
UPDATE `trinity_string` SET `entry` = 41,`content_default` = '显示' WHERE `trinity_string`.`entry` = 41;
UPDATE `trinity_string` SET `entry` = 42,`content_default` = '隐藏' WHERE `trinity_string`.`entry` = 42;
UPDATE `trinity_string` SET `entry` = 43,`content_default` = '完成' WHERE `trinity_string`.`entry` = 43;
UPDATE `trinity_string` SET `entry` = 44,`content_default` = '你' WHERE `trinity_string`.`entry` = 44;
UPDATE `trinity_string` SET `entry` = 45,`content_default` = ' <未知> ' WHERE `trinity_string`.`entry` = 45;
UPDATE `trinity_string` SET `entry` = 46,`content_default` = '<错误>' WHERE `trinity_string`.`entry` = 46;
UPDATE `trinity_string` SET `entry` = 47,`content_default` = '<查无此人>' WHERE `trinity_string`.`entry` = 47;
UPDATE `trinity_string` SET `entry` = 48,`content_default` = '未知' WHERE `trinity_string`.`entry` = 48;
UPDATE `trinity_string` SET `entry` = 49,`content_default` = '你必须达到 %u 级后进入.' WHERE `trinity_string`.`entry` = 49;
UPDATE `trinity_string` SET `entry` = 50,`content_default` = '你必须达到 %u 级,并且拥有道具 %s 方可进入.' WHERE `trinity_string`.`entry` = 50;
UPDATE `trinity_string` SET `entry` = 51,`content_default` = '你好! 准备学习什么技能吗?' WHERE `trinity_string`.`entry` = 51;
UPDATE `trinity_string` SET `entry` = 52,`content_default` = 'Invaid item count (%u) for item %u' WHERE `trinity_string`.`entry` = 52;
UPDATE `trinity_string` SET `entry` = 53,`content_default` = 'Mail can''t have more %u item stacks' WHERE `trinity_string`.`entry` = 53;
UPDATE `trinity_string` SET `entry` = 54,`content_default` = 'The new passwords do not match' WHERE `trinity_string`.`entry` = 54;
UPDATE `trinity_string` SET `entry` = 55,`content_default` = 'Your password can''t be longer than 16 characters (client limit), password not changed!' WHERE `trinity_string`.`entry` = 55;
UPDATE `trinity_string` SET `entry` = 56,`content_default` = 'Current Message of the day: \r\n%s' WHERE `trinity_string`.`entry` = 56;
UPDATE `trinity_string` SET `entry` = 57,`content_default` = 'Using World DB: %s' WHERE `trinity_string`.`entry` = 57;
UPDATE `trinity_string` SET `entry` = 58,`content_default` = 'Using script library: %s' WHERE `trinity_string`.`entry` = 58;
UPDATE `trinity_string` SET `entry` = 59,`content_default` = 'Using creature EventAI: %s' WHERE `trinity_string`.`entry` = 59;
UPDATE `trinity_string` SET `entry` = 60,`content_default` = 'Online players: %u (max: %u)' WHERE `trinity_string`.`entry` = 60;
UPDATE `trinity_string` SET `entry` = 61,`content_default` = 'Up to %u expansion allowed now.' WHERE `trinity_string`.`entry` = 61;
UPDATE `trinity_string` SET `entry` = 100,`content_default` = '世界通报:\\n' WHERE `trinity_string`.`entry` = 100;
UPDATE `trinity_string` SET `entry` = 101,`content_default` = '地图: %u (%s) 地域: %u (%s) 地区: %u (%s) Phase: %u\nX: %f Y: %f Z: %f Orientation: %f\ngrid[%u,%u]cell[%u,%u] InstanceID: %u\n ZoneX: %f ZoneY: %f\nGroundZ: %f FloorZ: %f Have height data (Map: %u VMap: %u)' WHERE `trinity_string`.`entry` = 101;
UPDATE `trinity_string` SET `entry` = 102,`content_default` = '%s 已被远距传送.' WHERE `trinity_string`.`entry` = 102;
UPDATE `trinity_string` SET `entry` = 103,`content_default` = '你可以召唤一个玩家到你的副本，前提是必须在同一队伍，而且你是队长.' WHERE `trinity_string`.`entry` = 103;
UPDATE `trinity_string` SET `entry` = 104,`content_default` = '你无法传送到玩家 %s 的副本，因为你们不在同一队伍.' WHERE `trinity_string`.`entry` = 104;
UPDATE `trinity_string` SET `entry` = 105,`content_default` = '传送到不是同一队伍的玩家 %s 的副本需要开启ＧＭ模式.' WHERE `trinity_string`.`entry` = 105;
UPDATE `trinity_string` SET `entry` = 106,`content_default` = '你无法传送到玩家  %s 从副本到副本.' WHERE `trinity_string`.`entry` = 106;
UPDATE `trinity_string` SET `entry` = 107,`content_default` = '你不能召唤这个玩家 %s 从副本到副本.' WHERE `trinity_string`.`entry` = 107;
UPDATE `trinity_string` SET `entry` = 108,`content_default` = '你正在召唤 %s%s.' WHERE `trinity_string`.`entry` = 108;
UPDATE `trinity_string` SET `entry` = 109,`content_default` = '系统提示：你正在被 %s 召唤中.' WHERE `trinity_string`.`entry` = 109;
UPDATE `trinity_string` SET `entry` = 110,`content_default` = '你正在传送  %s%s to %s.' WHERE `trinity_string`.`entry` = 110;
UPDATE `trinity_string` SET `entry` = 111,`content_default` = '系统提示：你正在被 %s 传送.' WHERE `trinity_string`.`entry` = 111;
UPDATE `trinity_string` SET `entry` = 112,`content_default` = '玩家 (%s) 不存在.' WHERE `trinity_string`.`entry` = 112;
UPDATE `trinity_string` SET `entry` = 113,`content_default` = '出现在 %s 的地点.' WHERE `trinity_string`.`entry` = 113;
UPDATE `trinity_string` SET `entry` = 114,`content_default` = '%s 出现在你的位置.' WHERE `trinity_string`.`entry` = 114;
UPDATE `trinity_string` SET `entry` = 115,`content_default` = '无效参数.' WHERE `trinity_string`.`entry` = 115;
UPDATE `trinity_string` SET `entry` = 116,`content_default` = '没有选定角色.' WHERE `trinity_string`.`entry` = 116;
UPDATE `trinity_string` SET `entry` = 117,`content_default` = '%s 不在同一小组里.' WHERE `trinity_string`.`entry` = 117;
UPDATE `trinity_string` SET `entry` = 118,`content_default` = '你改变了 %s 的血量值 HP to %i/%i.' WHERE `trinity_string`.`entry` = 118;
UPDATE `trinity_string` SET `entry` = 119,`content_default` = '%s 改变了你的血量值 HP 到 %i/%i.' WHERE `trinity_string`.`entry` = 119;
UPDATE `trinity_string` SET `entry` = 120,`content_default` = '你改变了 %s 的魔法值 MANA 到 %i/%i.' WHERE `trinity_string`.`entry` = 120;
UPDATE `trinity_string` SET `entry` = 121,`content_default` = '%s 改变了你的魔法值 MANA 到 %i/%i.' WHERE `trinity_string`.`entry` = 121;
UPDATE `trinity_string` SET `entry` = 122,`content_default` = '你改变了 %s 的能量值 ENERGY 到 %i/%i.' WHERE `trinity_string`.`entry` = 122;
UPDATE `trinity_string` SET `entry` = 123,`content_default` = '%s 改变了你的能量值 ENERGY 到 %i/%i.' WHERE `trinity_string`.`entry` = 123;
UPDATE `trinity_string` SET `entry` = 124,`content_default` = '当前的能量: %u' WHERE `trinity_string`.`entry` = 124;
UPDATE `trinity_string` SET `entry` = 125,`content_default` = '你改变了 %s 的怒气值 RAGE 到 %i/%i.' WHERE `trinity_string`.`entry` = 125;
UPDATE `trinity_string` SET `entry` = 126,`content_default` = '%s 改变了你的怒气值 RAGE 到 %i/%i.' WHERE `trinity_string`.`entry` = 126;
UPDATE `trinity_string` SET `entry` = 127,`content_default` = '你改变了 %s 的等级 LVL 到 %i.' WHERE `trinity_string`.`entry` = 127;
UPDATE `trinity_string` SET `entry` = 128,`content_default` = 'GUID %i, faction is %i, flags is %i, npcflag is %i' WHERE `trinity_string`.`entry` = 128;
UPDATE `trinity_string` SET `entry` = 129,`content_default` = '错误 faction: %u (not found in factiontemplate.dbc).' WHERE `trinity_string`.`entry` = 129;
UPDATE `trinity_string` SET `entry` = 130,`content_default` = '你改变了 GUID=%i ''s Faction to %i, flags to %i,' WHERE `trinity_string`.`entry` = 130;
UPDATE `trinity_string` SET `entry` = 131,`content_default` = '你改变了 the spellflatid=%i, val= %i, mark =%i ' WHERE `trinity_string`.`entry` = 131;
UPDATE `trinity_string` SET `entry` = 132,`content_default` = '%s 改变了你的 spellflatid=%i, val= %i, mark =%i.' WHERE `trinity_string`.`entry` = 132;
UPDATE `trinity_string` SET `entry` = 133,`content_default` = '%s 获得了所有的计程节点 (直到注销).' WHERE `trinity_string`.`entry` = 133;
UPDATE `trinity_string` SET `entry` = 134,`content_default` = '%s 没有更多地可获得的计程节点(仅显示容易接近的).' WHERE `trinity_string`.`entry` = 134;
UPDATE `trinity_string` SET `entry` = 135,`content_default` = '%s 给你进入所有计程车节点 (直到注销).' WHERE `trinity_string`.`entry` = 135;
UPDATE `trinity_string` SET `entry` = 136,`content_default` = '%s 已取消进出所有计程车节点(仅显示仍然容易接近的).' WHERE `trinity_string`.`entry` = 136;
UPDATE `trinity_string` SET `entry` = 137,`content_default` = '你设置了所有的速度到 %2.2f 从基础值 %s.' WHERE `trinity_string`.`entry` = 137;
UPDATE `trinity_string` SET `entry` = 138,`content_default` = '%s 设置了你所有的速度到 %2.2f 从基础值.' WHERE `trinity_string`.`entry` = 138;
UPDATE `trinity_string` SET `entry` = 139,`content_default` = '你设置了移动速度到 %2.2f 从基础值 %s.' WHERE `trinity_string`.`entry` = 139;
UPDATE `trinity_string` SET `entry` = 140,`content_default` = '%s 设置了你的移动速度到 %2.2f 从基础值.' WHERE `trinity_string`.`entry` = 140;
UPDATE `trinity_string` SET `entry` = 141,`content_default` = '你设置了游泳速度到 %2.2f 从基础值 %s.' WHERE `trinity_string`.`entry` = 141;
UPDATE `trinity_string` SET `entry` = 142,`content_default` = '%s 设置了你的游泳速度到 %2.2f 从基础值.' WHERE `trinity_string`.`entry` = 142;
UPDATE `trinity_string` SET `entry` = 143,`content_default` = '设置了后退速度到 %2.2f 从基础值 %s.' WHERE `trinity_string`.`entry` = 143;
UPDATE `trinity_string` SET `entry` = 144,`content_default` = '%s 设置了你的后退速度到 %2.2f 从基础值.' WHERE `trinity_string`.`entry` = 144;
UPDATE `trinity_string` SET `entry` = 145,`content_default` = '你设置了飞行速度到 %2.2f 从基础值 %s.' WHERE `trinity_string`.`entry` = 145;
UPDATE `trinity_string` SET `entry` = 146,`content_default` = '%s 设置你的飞行速度到 %2.2f 从基础值.' WHERE `trinity_string`.`entry` = 146;
UPDATE `trinity_string` SET `entry` = 147,`content_default` = '你设置了这个比例 %2.2f of %s.' WHERE `trinity_string`.`entry` = 147;
UPDATE `trinity_string` SET `entry` = 148,`content_default` = '%s 设置你的比例为 %2.2f.' WHERE `trinity_string`.`entry` = 148;
UPDATE `trinity_string` SET `entry` = 149,`content_default` = '没有此类骑术.' WHERE `trinity_string`.`entry` = 149;
UPDATE `trinity_string` SET `entry` = 150,`content_default` = '你把一个骑术送给 %s.' WHERE `trinity_string`.`entry` = 150;
UPDATE `trinity_string` SET `entry` = 151,`content_default` = '%s 送给你一个骑术.' WHERE `trinity_string`.`entry` = 151;
UPDATE `trinity_string` SET `entry` = 152,`content_default` = 'USER1: %i, ADD: %i, DIF: %i\n' WHERE `trinity_string`.`entry` = 152;
UPDATE `trinity_string` SET `entry` = 153,`content_default` = '你拿走了所有的铜币从 %s.' WHERE `trinity_string`.`entry` = 153;
UPDATE `trinity_string` SET `entry` = 154,`content_default` = '%s 拿走了你所有的铜币.' WHERE `trinity_string`.`entry` = 154;
UPDATE `trinity_string` SET `entry` = 155,`content_default` = '你拿走了 %i 铜币从 %s.' WHERE `trinity_string`.`entry` = 155;
UPDATE `trinity_string` SET `entry` = 156,`content_default` = '%s 拿走了 %i 铜币从你这里.' WHERE `trinity_string`.`entry` = 156;
UPDATE `trinity_string` SET `entry` = 157,`content_default` = '你把 %i 铜币给了 %s.' WHERE `trinity_string`.`entry` = 157;
UPDATE `trinity_string` SET `entry` = 158,`content_default` = '%s 给你 %i  铜币.' WHERE `trinity_string`.`entry` = 158;
UPDATE `trinity_string` SET `entry` = 159,`content_default` = '你听到声音 %u.' WHERE `trinity_string`.`entry` = 159;
UPDATE `trinity_string` SET `entry` = 160,`content_default` = 'USER2: %i, ADD: %i, RESULT: %i\n' WHERE `trinity_string`.`entry` = 160;
UPDATE `trinity_string` SET `entry` = 161,`content_default` = 'Removed bit %i in field %i.' WHERE `trinity_string`.`entry` = 161;
UPDATE `trinity_string` SET `entry` = 162,`content_default` = 'Set bit %i in field %i.' WHERE `trinity_string`.`entry` = 162;
UPDATE `trinity_string` SET `entry` = 163,`content_default` = '远距传送地点表是空的!' WHERE `trinity_string`.`entry` = 163;
UPDATE `trinity_string` SET `entry` = 164,`content_default` = '远距传送地点没被发现!' WHERE `trinity_string`.`entry` = 164;
UPDATE `trinity_string` SET `entry` = 165,`content_default` = '需要搜索参数.' WHERE `trinity_string`.`entry` = 165;
UPDATE `trinity_string` SET `entry` = 166,`content_default` = '没有远距传物地点匹配您的请求.' WHERE `trinity_string`.`entry` = 166;
UPDATE `trinity_string` SET `entry` = 168,`content_default` = '发现地点是: ' WHERE `trinity_string`.`entry` = 168;
UPDATE `trinity_string` SET `entry` = 169,`content_default` = '邮件寄给 %s' WHERE `trinity_string`.`entry` = 169;
UPDATE `trinity_string` SET `entry` = 170,`content_default` = '你试着听声音 %u 但是它并不存在.' WHERE `trinity_string`.`entry` = 170;
UPDATE `trinity_string` SET `entry` = 171,`content_default` = 'You can''t teleport self to self!' WHERE `trinity_string`.`entry` = 171;
UPDATE `trinity_string` SET `entry` = 172,`content_default` = '%s changed your runes to %i/%i/%i/%i/%i/%i.' WHERE `trinity_string`.`entry` = 172;
UPDATE `trinity_string` SET `entry` = 173,`content_default` = 'Current runes: %u/%u/%u/%u/%u/%u' WHERE `trinity_string`.`entry` = 173;
UPDATE `trinity_string` SET `entry` = 174,`content_default` = 'You changed runic power of %s to %i/%i.' WHERE `trinity_string`.`entry` = 174;
UPDATE `trinity_string` SET `entry` = 175,`content_default` = 'Liquid level: %f, ground: %f, type: %d, status: %d' WHERE `trinity_string`.`entry` = 175;
UPDATE `trinity_string` SET `entry` = 200,`content_default` = '没有选择.' WHERE `trinity_string`.`entry` = 200;
UPDATE `trinity_string` SET `entry` = 201,`content_default` = 'Object GUID is: lowpart %u highpart %X' WHERE `trinity_string`.`entry` = 201;
UPDATE `trinity_string` SET `entry` = 202,`content_default` = '这个名字长度超过了 %i 字符.' WHERE `trinity_string`.`entry` = 202;
UPDATE `trinity_string` SET `entry` = 203,`content_default` = '错误,名字只能包含字符 A-Z 和 a-z.' WHERE `trinity_string`.`entry` = 203;
UPDATE `trinity_string` SET `entry` = 204,`content_default` = '次级名字太长超过了 %i 字符.' WHERE `trinity_string`.`entry` = 204;
UPDATE `trinity_string` SET `entry` = 205,`content_default` = '未能实施.' WHERE `trinity_string`.`entry` = 205;
UPDATE `trinity_string` SET `entry` = 206,`content_default` = '物品 ''%i'' ''%s'' 以加入到列表且最大数 ''%i'' 复生时间 ''%i''' WHERE `trinity_string`.`entry` = 206;
UPDATE `trinity_string` SET `entry` = 207,`content_default` = '物品 ''%i'' 在数据库里没有找到.' WHERE `trinity_string`.`entry` = 207;
UPDATE `trinity_string` SET `entry` = 208,`content_default` = '物品 ''%i'' ''%s'' 已经从商人列表中删除.' WHERE `trinity_string`.`entry` = 208;
UPDATE `trinity_string` SET `entry` = 209,`content_default` = '物品 ''%i'' 没有找到在商人的列表里.' WHERE `trinity_string`.`entry` = 209;
UPDATE `trinity_string` SET `entry` = 210,`content_default` = '物品 ''%i'' 已经在商人的列表里存在了.' WHERE `trinity_string`.`entry` = 210;
UPDATE `trinity_string` SET `entry` = 211,`content_default` = '法术 %s 重置.' WHERE `trinity_string`.`entry` = 211;
UPDATE `trinity_string` SET `entry` = 212,`content_default` = '法术 %s 将在下次登陆时重置.' WHERE `trinity_string`.`entry` = 212;
UPDATE `trinity_string` SET `entry` = 213,`content_default` = '天赋 %s 重置.' WHERE `trinity_string`.`entry` = 213;
UPDATE `trinity_string` SET `entry` = 214,`content_default` = '天赋 %s 将在下次登陆时重置.' WHERE `trinity_string`.`entry` = 214;
UPDATE `trinity_string` SET `entry` = 215,`content_default` = '你的法术已经重置了.' WHERE `trinity_string`.`entry` = 215;
UPDATE `trinity_string` SET `entry` = 216,`content_default` = '你的天赋已经重置了.' WHERE `trinity_string`.`entry` = 216;
UPDATE `trinity_string` SET `entry` = 217,`content_default` = '未知的参数 ''%s'' 为 .resetall 命令. 键入完整的正确参数名字.' WHERE `trinity_string`.`entry` = 217;
UPDATE `trinity_string` SET `entry` = 218,`content_default` = '法术将重置在所有玩家在重新登录后. 强烈推荐重新登录!' WHERE `trinity_string`.`entry` = 218;
UPDATE `trinity_string` SET `entry` = 219,`content_default` = '天赋将重置在所有玩家在重新登录后. 强烈推荐重新登录!' WHERE `trinity_string`.`entry` = 219;
UPDATE `trinity_string` SET `entry` = 220,`content_default` = '生物 (GUID: %u) 没有飞行点发现.' WHERE `trinity_string`.`entry` = 220;
UPDATE `trinity_string` SET `entry` = 221,`content_default` = '生物 (GUID: %u) 飞行终点没有找到.' WHERE `trinity_string`.`entry` = 221;
UPDATE `trinity_string` SET `entry` = 222,`content_default` = '生物 (GUID: %u) 没有飞行点发现 - 请用  ''wpguid''. 现在设法发现它由它的位置...' WHERE `trinity_string`.`entry` = 222;
UPDATE `trinity_string` SET `entry` = 223,`content_default` = '生物 (GUID: %u) 没有飞行点发现 - 这是一个MaNGOS db 问题 (single float).' WHERE `trinity_string`.`entry` = 223;
UPDATE `trinity_string` SET `entry` = 224,`content_default` = '选择的生物被忽略 - 提供的 GUID 已经被占用.' WHERE `trinity_string`.`entry` = 224;
UPDATE `trinity_string` SET `entry` = 225,`content_default` = '生物 (GUID: %u) 没有找到.' WHERE `trinity_string`.`entry` = 225;
UPDATE `trinity_string` SET `entry` = 226,`content_default` = '您必须选择一个视觉飞行点.' WHERE `trinity_string`.`entry` = 226;
UPDATE `trinity_string` SET `entry` = 227,`content_default` = '没有找到视觉飞行点.' WHERE `trinity_string`.`entry` = 227;
UPDATE `trinity_string` SET `entry` = 228,`content_default` = '不能创建视觉飞行点的 生物ID: %d' WHERE `trinity_string`.`entry` = 228;
UPDATE `trinity_string` SET `entry` = 229,`content_default` = '所有视觉飞行点消除.' WHERE `trinity_string`.`entry` = 229;
UPDATE `trinity_string` SET `entry` = 230,`content_default` = '不能创建 飞行点-生物的 ID: %d' WHERE `trinity_string`.`entry` = 230;
UPDATE `trinity_string` SET `entry` = 231,`content_default` = '没有 GUID 被提供.' WHERE `trinity_string`.`entry` = 231;
UPDATE `trinity_string` SET `entry` = 232,`content_default` = '没有提供飞行点数值.' WHERE `trinity_string`.`entry` = 232;
UPDATE `trinity_string` SET `entry` = 233,`content_default` = '根据要求为 ''%s''.' WHERE `trinity_string`.`entry` = 233;
UPDATE `trinity_string` SET `entry` = 234,`content_default` = '飞行点 %i 添加到 GUID: %d' WHERE `trinity_string`.`entry` = 234;
UPDATE `trinity_string` SET `entry` = 235,`content_default` = '飞行点 %d 已添加.' WHERE `trinity_string`.`entry` = 235;
UPDATE `trinity_string` SET `entry` = 236,`content_default` = '飞行点已变动.' WHERE `trinity_string`.`entry` = 236;
UPDATE `trinity_string` SET `entry` = 237,`content_default` = '飞行点 %s 已修改.' WHERE `trinity_string`.`entry` = 237;
UPDATE `trinity_string` SET `entry` = 238,`content_default` = '飞行点出口成功.' WHERE `trinity_string`.`entry` = 238;
UPDATE `trinity_string` SET `entry` = 239,`content_default` = '没有飞行点被发现在数据库里.' WHERE `trinity_string`.`entry` = 239;
UPDATE `trinity_string` SET `entry` = 240,`content_default` = '文件已导入.' WHERE `trinity_string`.`entry` = 240;
UPDATE `trinity_string` SET `entry` = 241,`content_default` = '飞行点取消.' WHERE `trinity_string`.`entry` = 241;
UPDATE `trinity_string` SET `entry` = 242,`content_default` = '警告: 不能删除这个飞行点从世界里且 ID: %d' WHERE `trinity_string`.`entry` = 242;
UPDATE `trinity_string` SET `entry` = 243,`content_default` = '出现这种情况，是因为飞行点过于远离你.' WHERE `trinity_string`.`entry` = 243;
UPDATE `trinity_string` SET `entry` = 244,`content_default` = '这个飞行点已经从数据库删除, 但不是从世界这里.' WHERE `trinity_string`.`entry` = 244;
UPDATE `trinity_string` SET `entry` = 245,`content_default` = '他们将消失，当服务器重新启动之后.' WHERE `trinity_string`.`entry` = 245;
UPDATE `trinity_string` SET `entry` = 246,`content_default` = '飞行点 %d: 生物信息: %s, GUID: %d' WHERE `trinity_string`.`entry` = 246;
UPDATE `trinity_string` SET `entry` = 247,`content_default` = '等待时间: %d' WHERE `trinity_string`.`entry` = 247;
UPDATE `trinity_string` SET `entry` = 248,`content_default` = '模型 %d: %d' WHERE `trinity_string`.`entry` = 248;
UPDATE `trinity_string` SET `entry` = 249,`content_default` = '表情: %d' WHERE `trinity_string`.`entry` = 249;
UPDATE `trinity_string` SET `entry` = 250,`content_default` = '技能: %d' WHERE `trinity_string`.`entry` = 250;
UPDATE `trinity_string` SET `entry` = 251,`content_default` = '文本%d (ID: %i): %s' WHERE `trinity_string`.`entry` = 251;
UPDATE `trinity_string` SET `entry` = 252,`content_default` = 'AI脚本: %s' WHERE `trinity_string`.`entry` = 252;
UPDATE `trinity_string` SET `entry` = 253,`content_default` = '强制修改玩家名 %s, 将于下次登录时生效.' WHERE `trinity_string`.`entry` = 253;
UPDATE `trinity_string` SET `entry` = 254,`content_default` = '强制修改玩家名 %s (GUID #%u), 将于下次登录时生效.' WHERE `trinity_string`.`entry` = 254;
UPDATE `trinity_string` SET `entry` = 255,`content_default` = '飞行点-生物 (GUID: %u) 没有找到.' WHERE `trinity_string`.`entry` = 255;
UPDATE `trinity_string` SET `entry` = 256,`content_default` = '不能查找NPC...' WHERE `trinity_string`.`entry` = 256;
UPDATE `trinity_string` SET `entry` = 257,`content_default` = '生物运动方式设置为 ''%s'', 飞行点去除 (如果任何).' WHERE `trinity_string`.`entry` = 257;
UPDATE `trinity_string` SET `entry` = 258,`content_default` = '生物运动方式设置为 ''%s'', 飞行点没有去除.' WHERE `trinity_string`.`entry` = 258;
UPDATE `trinity_string` SET `entry` = 259,`content_default` = '错误值, 请用 on 或 off ' WHERE `trinity_string`.`entry` = 259;
UPDATE `trinity_string` SET `entry` = 260,`content_default` = '设置已保存.' WHERE `trinity_string`.`entry` = 260;
UPDATE `trinity_string` SET `entry` = 261,`content_default` = '设置已保存, 你可能需要重新清理你的客户缓存.' WHERE `trinity_string`.`entry` = 261;
UPDATE `trinity_string` SET `entry` = 262,`content_default` = '区域触发(传送门) ID %u 没有发现! ' WHERE `trinity_string`.`entry` = 262;
UPDATE `trinity_string` SET `entry` = 263,`content_default` = '目标地图或坐标无效 (X: %f Y: %f MapId: %u)' WHERE `trinity_string`.`entry` = 263;
UPDATE `trinity_string` SET `entry` = 264,`content_default` = '区域传送门无效 (X: %f Y: %f AreaId: %u)' WHERE `trinity_string`.`entry` = 264;
UPDATE `trinity_string` SET `entry` = 265,`content_default` = 'Zone %u (%s) is part of instanceable map %u (%s)' WHERE `trinity_string`.`entry` = 265;
UPDATE `trinity_string` SET `entry` = 266,`content_default` = '没任何发现!' WHERE `trinity_string`.`entry` = 266;
UPDATE `trinity_string` SET `entry` = 267,`content_default` = '对象没有找到!' WHERE `trinity_string`.`entry` = 267;
UPDATE `trinity_string` SET `entry` = 268,`content_default` = '生物没有找到!' WHERE `trinity_string`.`entry` = 268;
UPDATE `trinity_string` SET `entry` = 269,`content_default` = '警告: 怪物发现超过一次 - 你将使用的是第一个在DB数据里的记录.' WHERE `trinity_string`.`entry` = 269;
UPDATE `trinity_string` SET `entry` = 270,`content_default` = '生物已经移除.' WHERE `trinity_string`.`entry` = 270;
UPDATE `trinity_string` SET `entry` = 271,`content_default` = '生物已经移动. ' WHERE `trinity_string`.`entry` = 271;
UPDATE `trinity_string` SET `entry` = 272,`content_default` = '生物 (GUID:%u) 必须与玩家在同样的地图!' WHERE `trinity_string`.`entry` = 272;
UPDATE `trinity_string` SET `entry` = 273,`content_default` = '游戏对象 (GUID: %u) 没有找到.' WHERE `trinity_string`.`entry` = 273;
UPDATE `trinity_string` SET `entry` = 274,`content_default` = '游戏对象 (GUID: %u) 有一个参考于没有找到生物 %u 是名单, 不能被删除.' WHERE `trinity_string`.`entry` = 274;
UPDATE `trinity_string` SET `entry` = 275,`content_default` = '游戏对象 (GUID: %u) 去除.' WHERE `trinity_string`.`entry` = 275;
UPDATE `trinity_string` SET `entry` = 276,`content_default` = '游戏对象 (GUID: %u) 转动.' WHERE `trinity_string`.`entry` = 276;
UPDATE `trinity_string` SET `entry` = 277,`content_default` = '游戏对象 (GUID: %u) 移动.' WHERE `trinity_string`.`entry` = 277;
UPDATE `trinity_string` SET `entry` = 278,`content_default` = '你必须选择一个商人' WHERE `trinity_string`.`entry` = 278;
UPDATE `trinity_string` SET `entry` = 279,`content_default` = '你必须使用物品的id' WHERE `trinity_string`.`entry` = 279;
UPDATE `trinity_string` SET `entry` = 280,`content_default` = '商人设置了太多的物品 (最多128)' WHERE `trinity_string`.`entry` = 280;
UPDATE `trinity_string` SET `entry` = 281,`content_default` = '你不能踢出你自己，使用退出代替.' WHERE `trinity_string`.`entry` = 281;
UPDATE `trinity_string` SET `entry` = 282,`content_default` = '角色 %s 已踢出.' WHERE `trinity_string`.`entry` = 282;
UPDATE `trinity_string` SET `entry` = 284,`content_default` = '接受悄悄话: %s' WHERE `trinity_string`.`entry` = 284;
UPDATE `trinity_string` SET `entry` = 285,`content_default` = '接受悄悄话: ON' WHERE `trinity_string`.`entry` = 285;
UPDATE `trinity_string` SET `entry` = 286,`content_default` = '接受悄悄话: OFF' WHERE `trinity_string`.`entry` = 286;
UPDATE `trinity_string` SET `entry` = 287,`content_default` = '生物 (GUID: %u) 没有找到.' WHERE `trinity_string`.`entry` = 287;
UPDATE `trinity_string` SET `entry` = 288,`content_default` = '票数量: %i 出示新的票: %s ' WHERE `trinity_string`.`entry` = 288;
UPDATE `trinity_string` SET `entry` = 289,`content_default` = '新票开始于 %s' WHERE `trinity_string`.`entry` = 289;
UPDATE `trinity_string` SET `entry` = 290,`content_default` = 'Ticket of %s (Last updated: %s):\n%s' WHERE `trinity_string`.`entry` = 290;
UPDATE `trinity_string` SET `entry` = 291,`content_default` = '新票显示: ON' WHERE `trinity_string`.`entry` = 291;
UPDATE `trinity_string` SET `entry` = 292,`content_default` = '新票显示: OFF' WHERE `trinity_string`.`entry` = 292;
UPDATE `trinity_string` SET `entry` = 293,`content_default` = '票 %i 不存在.' WHERE `trinity_string`.`entry` = 293;
UPDATE `trinity_string` SET `entry` = 294,`content_default` = '所有票已删除.' WHERE `trinity_string`.`entry` = 294;
UPDATE `trinity_string` SET `entry` = 295,`content_default` = '角色 %s 票已删除.' WHERE `trinity_string`.`entry` = 295;
UPDATE `trinity_string` SET `entry` = 296,`content_default` = '票已删除.' WHERE `trinity_string`.`entry` = 296;
UPDATE `trinity_string` SET `entry` = 297,`content_default` = '复生间隔改变为: %i' WHERE `trinity_string`.`entry` = 297;
UPDATE `trinity_string` SET `entry` = 298,`content_default` = '复生时间改变为: %i' WHERE `trinity_string`.`entry` = 298;
UPDATE `trinity_string` SET `entry` = 299,`content_default` = ' %s 的荣誉被设置到 %u!' WHERE `trinity_string`.`entry` = 299;
UPDATE `trinity_string` SET `entry` = 300,`content_default` = '你的闲谈将被关闭 %u 分钟.' WHERE `trinity_string`.`entry` = 300;
UPDATE `trinity_string` SET `entry` = 301,`content_default` = '你被关闭了 %s 的聊天时间 %u 分钟.' WHERE `trinity_string`.`entry` = 301;
UPDATE `trinity_string` SET `entry` = 302,`content_default` = '玩的聊天已经可以使用.' WHERE `trinity_string`.`entry` = 302;
UPDATE `trinity_string` SET `entry` = 303,`content_default` = '你的聊天已经可以使用.' WHERE `trinity_string`.`entry` = 303;
UPDATE `trinity_string` SET `entry` = 304,`content_default` = '你已经可以使用 %s 的聊天了.' WHERE `trinity_string`.`entry` = 304;
UPDATE `trinity_string` SET `entry` = 305,`content_default` = 'Faction %s (%u) reputation of %s was set to %5d!' WHERE `trinity_string`.`entry` = 305;
UPDATE `trinity_string` SET `entry` = 306,`content_default` = 'The arena points of %s was set to %u!' WHERE `trinity_string`.`entry` = 306;
UPDATE `trinity_string` SET `entry` = 307,`content_default` = '没有阵营被发现' WHERE `trinity_string`.`entry` = 307;
UPDATE `trinity_string` SET `entry` = 308,`content_default` = '阵营 %i 未知!' WHERE `trinity_string`.`entry` = 308;
UPDATE `trinity_string` SET `entry` = 309,`content_default` = '无效的参数 %s' WHERE `trinity_string`.`entry` = 309;
UPDATE `trinity_string` SET `entry` = 310,`content_default` = 'delta must be between 0 and %d (inclusive)' WHERE `trinity_string`.`entry` = 310;
UPDATE `trinity_string` SET `entry` = 311,`content_default` = '%d - |cffffffff|Hfaction:%d|h[%s]|h|r' WHERE `trinity_string`.`entry` = 311;
UPDATE `trinity_string` SET `entry` = 312,`content_default` = ' [visible]' WHERE `trinity_string`.`entry` = 312;
UPDATE `trinity_string` SET `entry` = 313,`content_default` = ' [at war]' WHERE `trinity_string`.`entry` = 313;
UPDATE `trinity_string` SET `entry` = 314,`content_default` = ' [peace forced]' WHERE `trinity_string`.`entry` = 314;
UPDATE `trinity_string` SET `entry` = 315,`content_default` = ' [hidden]' WHERE `trinity_string`.`entry` = 315;
UPDATE `trinity_string` SET `entry` = 316,`content_default` = ' [invisible forced]' WHERE `trinity_string`.`entry` = 316;
UPDATE `trinity_string` SET `entry` = 317,`content_default` = ' [inactive]' WHERE `trinity_string`.`entry` = 317;
UPDATE `trinity_string` SET `entry` = 318,`content_default` = '仇恨' WHERE `trinity_string`.`entry` = 318;
UPDATE `trinity_string` SET `entry` = 319,`content_default` = '敌对' WHERE `trinity_string`.`entry` = 319;
UPDATE `trinity_string` SET `entry` = 320,`content_default` = '不友好' WHERE `trinity_string`.`entry` = 320;
UPDATE `trinity_string` SET `entry` = 321,`content_default` = '中立' WHERE `trinity_string`.`entry` = 321;
UPDATE `trinity_string` SET `entry` = 322,`content_default` = '友好的' WHERE `trinity_string`.`entry` = 322;
UPDATE `trinity_string` SET `entry` = 323,`content_default` = '荣誉的' WHERE `trinity_string`.`entry` = 323;
UPDATE `trinity_string` SET `entry` = 324,`content_default` = '尊敬的' WHERE `trinity_string`.`entry` = 324;
UPDATE `trinity_string` SET `entry` = 325,`content_default` = '高贵的' WHERE `trinity_string`.`entry` = 325;
UPDATE `trinity_string` SET `entry` = 326,`content_default` = 'Faction %s (%u) can''not have reputation.' WHERE `trinity_string`.`entry` = 326;
UPDATE `trinity_string` SET `entry` = 327,`content_default` = ' [no reputation]' WHERE `trinity_string`.`entry` = 327;
UPDATE `trinity_string` SET `entry` = 328,`content_default` = 'Characters at account %s (Id: %u)' WHERE `trinity_string`.`entry` = 328;
UPDATE `trinity_string` SET `entry` = 329,`content_default` = '  %s (GUID %u)' WHERE `trinity_string`.`entry` = 329;
UPDATE `trinity_string` SET `entry` = 330,`content_default` = 'No players found!' WHERE `trinity_string`.`entry` = 330;
UPDATE `trinity_string` SET `entry` = 331,`content_default` = 'Extended item cost %u not exist' WHERE `trinity_string`.`entry` = 331;
UPDATE `trinity_string` SET `entry` = 332,`content_default` = 'GM 模式开启' WHERE `trinity_string`.`entry` = 332;
UPDATE `trinity_string` SET `entry` = 333,`content_default` = 'GM 模式关闭' WHERE `trinity_string`.`entry` = 333;
UPDATE `trinity_string` SET `entry` = 334,`content_default` = 'GM Chat Badge is ON' WHERE `trinity_string`.`entry` = 334;
UPDATE `trinity_string` SET `entry` = 335,`content_default` = 'GM Chat Badge is OFF' WHERE `trinity_string`.`entry` = 335;
UPDATE `trinity_string` SET `entry` = 336,`content_default` = 'You repair all %s''s items.' WHERE `trinity_string`.`entry` = 336;
UPDATE `trinity_string` SET `entry` = 337,`content_default` = 'All your items repaired by %s.' WHERE `trinity_string`.`entry` = 337;
UPDATE `trinity_string` SET `entry` = 338,`content_default` = 'You set waterwalk mode %s for %s.' WHERE `trinity_string`.`entry` = 338;
UPDATE `trinity_string` SET `entry` = 339,`content_default` = 'Your waterwalk mode %s by %s.' WHERE `trinity_string`.`entry` = 339;
UPDATE `trinity_string` SET `entry` = 340,`content_default` = '%s is now following you.' WHERE `trinity_string`.`entry` = 340;
UPDATE `trinity_string` SET `entry` = 341,`content_default` = '%s is not following you.' WHERE `trinity_string`.`entry` = 341;
UPDATE `trinity_string` SET `entry` = 342,`content_default` = '%s is now not following you.' WHERE `trinity_string`.`entry` = 342;
UPDATE `trinity_string` SET `entry` = 343,`content_default` = 'Creature (Entry: %u) cannot be tamed.' WHERE `trinity_string`.`entry` = 343;
UPDATE `trinity_string` SET `entry` = 344,`content_default` = 'You already have pet.' WHERE `trinity_string`.`entry` = 344;
UPDATE `trinity_string` SET `entry` = 345,`content_default` = 'Forced customize for player %s will be requested at next login.' WHERE `trinity_string`.`entry` = 345;
UPDATE `trinity_string` SET `entry` = 346,`content_default` = 'Forced customize for player %s (GUID #%u) will be requested at next login.' WHERE `trinity_string`.`entry` = 346;
UPDATE `trinity_string` SET `entry` = 347,`content_default` = 'TaxiNode ID %u not found!' WHERE `trinity_string`.`entry` = 347;
UPDATE `trinity_string` SET `entry` = 348,`content_default` = 'Game Object (Entry: %u) have invalid data and can''t be spawned' WHERE `trinity_string`.`entry` = 348;
UPDATE `trinity_string` SET `entry` = 400,`content_default` = '|cffff0000[系统信息]:|rScripts reloaded' WHERE `trinity_string`.`entry` = 400;
UPDATE `trinity_string` SET `entry` = 401,`content_default` = '你改变了 %s 的安全等级为 %i.' WHERE `trinity_string`.`entry` = 401;
UPDATE `trinity_string` SET `entry` = 402,`content_default` = '%s 改变了你的安全等级为 %i.' WHERE `trinity_string`.`entry` = 402;
UPDATE `trinity_string` SET `entry` = 403,`content_default` = '你这是低的防护等级.' WHERE `trinity_string`.`entry` = 403;
UPDATE `trinity_string` SET `entry` = 404,`content_default` = '生物移动点取消.' WHERE `trinity_string`.`entry` = 404;
UPDATE `trinity_string` SET `entry` = 405,`content_default` = '生物移动点生效.' WHERE `trinity_string`.`entry` = 405;
UPDATE `trinity_string` SET `entry` = 406,`content_default` = '这个区域的天气不能被更改.' WHERE `trinity_string`.`entry` = 406;
UPDATE `trinity_string` SET `entry` = 407,`content_default` = '本服务器天气系统取消.' WHERE `trinity_string`.`entry` = 407;
UPDATE `trinity_string` SET `entry` = 408,`content_default` = '%s 被禁止的为 %s. 操作: %s.' WHERE `trinity_string`.`entry` = 408;
UPDATE `trinity_string` SET `entry` = 409,`content_default` = '%s 被永久禁止的为 %s.' WHERE `trinity_string`.`entry` = 409;
UPDATE `trinity_string` SET `entry` = 410,`content_default` = '%s %s 没有发现.' WHERE `trinity_string`.`entry` = 410;
UPDATE `trinity_string` SET `entry` = 411,`content_default` = '%s 已解除禁止.' WHERE `trinity_string`.`entry` = 411;
UPDATE `trinity_string` SET `entry` = 412,`content_default` = '出现错误取消禁令 %s.' WHERE `trinity_string`.`entry` = 412;
UPDATE `trinity_string` SET `entry` = 413,`content_default` = '没有这个帐户.' WHERE `trinity_string`.`entry` = 413;
UPDATE `trinity_string` SET `entry` = 414,`content_default` = '没有这个角色.' WHERE `trinity_string`.`entry` = 414;
UPDATE `trinity_string` SET `entry` = 415,`content_default` = '没有这样的IP 在禁止名单.' WHERE `trinity_string`.`entry` = 415;
UPDATE `trinity_string` SET `entry` = 416,`content_default` = '账号 %s 从来没被禁止.' WHERE `trinity_string`.`entry` = 416;
UPDATE `trinity_string` SET `entry` = 417,`content_default` = '历史禁止帐户 %s:' WHERE `trinity_string`.`entry` = 417;
UPDATE `trinity_string` SET `entry` = 418,`content_default` = '禁止日期: %s 禁止时间: %s 激活间隔: %s  原因: %s 操作者: %s' WHERE `trinity_string`.`entry` = 418;
UPDATE `trinity_string` SET `entry` = 419,`content_default` = 'Inf.' WHERE `trinity_string`.`entry` = 419;
UPDATE `trinity_string` SET `entry` = 420,`content_default` = 'Never' WHERE `trinity_string`.`entry` = 420;
UPDATE `trinity_string` SET `entry` = 421,`content_default` = 'Yes' WHERE `trinity_string`.`entry` = 421;
UPDATE `trinity_string` SET `entry` = 422,`content_default` = 'No' WHERE `trinity_string`.`entry` = 422;
UPDATE `trinity_string` SET `entry` = 423,`content_default` = 'IP地址: %s 禁止日期: %s 解除禁止日期: %s 剩余: %s R' WHERE `trinity_string`.`entry` = 423;
UPDATE `trinity_string` SET `entry` = 424,`content_default` = '没有匹配的IP禁止地址.' WHERE `trinity_string`.`entry` = 424;
UPDATE `trinity_string` SET `entry` = 425,`content_default` = '没有匹配的帐户.' WHERE `trinity_string`.`entry` = 425;
UPDATE `trinity_string` SET `entry` = 426,`content_default` = '没有禁用的账号相匹配.' WHERE `trinity_string`.`entry` = 426;
UPDATE `trinity_string` SET `entry` = 427,`content_default` = '下面的IP地址符合您的格局:' WHERE `trinity_string`.`entry` = 427;
UPDATE `trinity_string` SET `entry` = 428,`content_default` = '以下帐户匹配您的查询:' WHERE `trinity_string`.`entry` = 428;
UPDATE `trinity_string` SET `entry` = 429,`content_default` = '你学会了许多法术或技能.' WHERE `trinity_string`.`entry` = 429;
UPDATE `trinity_string` SET `entry` = 430,`content_default` = '你已经学会了所有的会职业法术.' WHERE `trinity_string`.`entry` = 430;
UPDATE `trinity_string` SET `entry` = 431,`content_default` = '你已经学会了所有的本职业天赋.' WHERE `trinity_string`.`entry` = 431;
UPDATE `trinity_string` SET `entry` = 432,`content_default` = '你已经学会了所有的语言.' WHERE `trinity_string`.`entry` = 432;
UPDATE `trinity_string` SET `entry` = 433,`content_default` = '你学会了所有手工艺技能和食谱.' WHERE `trinity_string`.`entry` = 433;
UPDATE `trinity_string` SET `entry` = 434,`content_default` = '不能查找 ''%s''' WHERE `trinity_string`.`entry` = 434;
UPDATE `trinity_string` SET `entry` = 435,`content_default` = '无效的物品 id: %u' WHERE `trinity_string`.`entry` = 435;
UPDATE `trinity_string` SET `entry` = 436,`content_default` = '没有找到物品!' WHERE `trinity_string`.`entry` = 436;
UPDATE `trinity_string` SET `entry` = 437,`content_default` = '无效的游戏物品对象 id: %u' WHERE `trinity_string`.`entry` = 437;
UPDATE `trinity_string` SET `entry` = 438,`content_default` = '找到物品 %u: %u ( 库存 %u 邮件 %u 拍卖 %u )' WHERE `trinity_string`.`entry` = 438;
UPDATE `trinity_string` SET `entry` = 439,`content_default` = '找到物品对象 %u: %u' WHERE `trinity_string`.`entry` = 439;
UPDATE `trinity_string` SET `entry` = 440,`content_default` = '无效的生物 id: %u' WHERE `trinity_string`.`entry` = 440;
UPDATE `trinity_string` SET `entry` = 441,`content_default` = '找到生物 %u: %u' WHERE `trinity_string`.`entry` = 441;
UPDATE `trinity_string` SET `entry` = 442,`content_default` = '没有地区被发现!' WHERE `trinity_string`.`entry` = 442;
UPDATE `trinity_string` SET `entry` = 443,`content_default` = '没有找到物品集!' WHERE `trinity_string`.`entry` = 443;
UPDATE `trinity_string` SET `entry` = 444,`content_default` = '没有找到此技能!' WHERE `trinity_string`.`entry` = 444;
UPDATE `trinity_string` SET `entry` = 445,`content_default` = '没有找到此法术!' WHERE `trinity_string`.`entry` = 445;
UPDATE `trinity_string` SET `entry` = 446,`content_default` = '没有找到此任务!' WHERE `trinity_string`.`entry` = 446;
UPDATE `trinity_string` SET `entry` = 447,`content_default` = '没有找到此生物!' WHERE `trinity_string`.`entry` = 447;
UPDATE `trinity_string` SET `entry` = 448,`content_default` = '没有找到此游戏物品对象!' WHERE `trinity_string`.`entry` = 448;
UPDATE `trinity_string` SET `entry` = 449,`content_default` = '墓地 #%u 不存在.' WHERE `trinity_string`.`entry` = 449;
UPDATE `trinity_string` SET `entry` = 450,`content_default` = '墓地 #%u 已经连接到区域 #%u (当前).' WHERE `trinity_string`.`entry` = 450;
UPDATE `trinity_string` SET `entry` = 451,`content_default` = '墓地 #%u 连接到区域 #%u (当前).' WHERE `trinity_string`.`entry` = 451;
UPDATE `trinity_string` SET `entry` = 452,`content_default` = '墓地 #%u 不能连接到子区域或不存在的区域 #%u (内部错误).' WHERE `trinity_string`.`entry` = 452;
UPDATE `trinity_string` SET `entry` = 454,`content_default` = '没有阵营在墓地且 id= #%u , 请修复你的DB数据库' WHERE `trinity_string`.`entry` = 454;
UPDATE `trinity_string` SET `entry` = 455,`content_default` = '错误的队伍, 请修复你的数据库' WHERE `trinity_string`.`entry` = 455;
UPDATE `trinity_string` SET `entry` = 456,`content_default` = '任何' WHERE `trinity_string`.`entry` = 456;
UPDATE `trinity_string` SET `entry` = 457,`content_default` = '联盟' WHERE `trinity_string`.`entry` = 457;
UPDATE `trinity_string` SET `entry` = 458,`content_default` = '部落' WHERE `trinity_string`.`entry` = 458;
UPDATE `trinity_string` SET `entry` = 459,`content_default` = '墓地ID #%u (阵营faction: %s) 是最近的距此区域zoneID #%u.' WHERE `trinity_string`.`entry` = 459;
UPDATE `trinity_string` SET `entry` = 460,`content_default` = '区域Zone #%u 没有一个连接的墓地.' WHERE `trinity_string`.`entry` = 460;
UPDATE `trinity_string` SET `entry` = 461,`content_default` = '区域Zone #%u 没有一个连接的墓地为阵营faction: %s.' WHERE `trinity_string`.`entry` = 461;
UPDATE `trinity_string` SET `entry` = 462,`content_default` = '远距传物地点已经存在!' WHERE `trinity_string`.`entry` = 462;
UPDATE `trinity_string` SET `entry` = 463,`content_default` = '远距传送地点增加.' WHERE `trinity_string`.`entry` = 463;
UPDATE `trinity_string` SET `entry` = 464,`content_default` = '远距传送地点没增加: 数据库错误.' WHERE `trinity_string`.`entry` = 464;
UPDATE `trinity_string` SET `entry` = 465,`content_default` = '远距传送地点被删除.' WHERE `trinity_string`.`entry` = 465;
UPDATE `trinity_string` SET `entry` = 466,`content_default` = 'No taxinodes found!' WHERE `trinity_string`.`entry` = 466;
UPDATE `trinity_string` SET `entry` = 467,`content_default` = '目标单位(unit)有 %d 光环auras:' WHERE `trinity_string`.`entry` = 467;
UPDATE `trinity_string` SET `entry` = 468,`content_default` = 'id: %d effmask: %d charges: %d stack: %d slot %d duration: %d maxduration: %d' WHERE `trinity_string`.`entry` = 468;
UPDATE `trinity_string` SET `entry` = 469,`content_default` = 'Target unit has %d auras of type %d:' WHERE `trinity_string`.`entry` = 469;
UPDATE `trinity_string` SET `entry` = 470,`content_default` = 'id: %d eff: %d amount: %d' WHERE `trinity_string`.`entry` = 470;
UPDATE `trinity_string` SET `entry` = 471,`content_default` = '任务 %u 没有找到.' WHERE `trinity_string`.`entry` = 471;
UPDATE `trinity_string` SET `entry` = 472,`content_default` = '任务 %u 由物品触发. 为正确工作, 请, 添加物品到库里并且开始这个任务的正常方式: .additem %u' WHERE `trinity_string`.`entry` = 472;
UPDATE `trinity_string` SET `entry` = 473,`content_default` = '任务清除.' WHERE `trinity_string`.`entry` = 473;
UPDATE `trinity_string` SET `entry` = 474,`content_default` = ' [奖赏]' WHERE `trinity_string`.`entry` = 474;
UPDATE `trinity_string` SET `entry` = 475,`content_default` = ' [完成]' WHERE `trinity_string`.`entry` = 475;
UPDATE `trinity_string` SET `entry` = 476,`content_default` = ' [active]' WHERE `trinity_string`.`entry` = 476;
UPDATE `trinity_string` SET `entry` = 477,`content_default` = '%s 的飞行模式为 %s' WHERE `trinity_string`.`entry` = 477;
UPDATE `trinity_string` SET `entry` = 478,`content_default` = '操作代码Opcode %u 发送到(sent to) %s' WHERE `trinity_string`.`entry` = 478;
UPDATE `trinity_string` SET `entry` = 479,`content_default` = '角色加载成功!' WHERE `trinity_string`.`entry` = 479;
UPDATE `trinity_string` SET `entry` = 480,`content_default` = '加载角色失败!' WHERE `trinity_string`.`entry` = 480;
UPDATE `trinity_string` SET `entry` = 481,`content_default` = '卸载角色成功!' WHERE `trinity_string`.`entry` = 481;
UPDATE `trinity_string` SET `entry` = 482,`content_default` = '卸载角色失败!' WHERE `trinity_string`.`entry` = 482;
UPDATE `trinity_string` SET `entry` = 483,`content_default` = '魔法 %u 破裂，并且不允许使用或学习!' WHERE `trinity_string`.`entry` = 483;
UPDATE `trinity_string` SET `entry` = 484,`content_default` = '技能值 %u (%s) 为角色 %s 设置到 %u 并且当前最大设置到 %u (没有固定(天赋)奖励).' WHERE `trinity_string`.`entry` = 484;
UPDATE `trinity_string` SET `entry` = 485,`content_default` = '角色 %s 必须拥有技能 %u (%s) 在使用这个命令之前.' WHERE `trinity_string`.`entry` = 485;
UPDATE `trinity_string` SET `entry` = 486,`content_default` = '错误的技能 id (%u)' WHERE `trinity_string`.`entry` = 486;
UPDATE `trinity_string` SET `entry` = 487,`content_default` = '你学会了ＧＭ默认的法术和技能.' WHERE `trinity_string`.`entry` = 487;
UPDATE `trinity_string` SET `entry` = 488,`content_default` = '你已经学了这个法术.' WHERE `trinity_string`.`entry` = 488;
UPDATE `trinity_string` SET `entry` = 489,`content_default` = '目标Target(%s) 已经学习了那些法术.' WHERE `trinity_string`.`entry` = 489;
UPDATE `trinity_string` SET `entry` = 490,`content_default` = '%s 不懂那些法术.' WHERE `trinity_string`.`entry` = 490;
UPDATE `trinity_string` SET `entry` = 491,`content_default` = '您已经忘记了那个法术.' WHERE `trinity_string`.`entry` = 491;
UPDATE `trinity_string` SET `entry` = 492,`content_default` = '所有的法术冷却清除 for %s.' WHERE `trinity_string`.`entry` = 492;
UPDATE `trinity_string` SET `entry` = 493,`content_default` = '法术 %u 冷却清除 for %s.' WHERE `trinity_string`.`entry` = 493;
UPDATE `trinity_string` SET `entry` = 494,`content_default` = '命令: Additem, itemId = %i, amount = %i' WHERE `trinity_string`.`entry` = 494;
UPDATE `trinity_string` SET `entry` = 495,`content_default` = '命令: Additemset, itemsetId = %i' WHERE `trinity_string`.`entry` = 495;
UPDATE `trinity_string` SET `entry` = 496,`content_default` = '移除物品ID = %i, amount = %i from %s' WHERE `trinity_string`.`entry` = 496;
UPDATE `trinity_string` SET `entry` = 497,`content_default` = '不能创建物品  ''%i'' (数量amount: %i)' WHERE `trinity_string`.`entry` = 497;
UPDATE `trinity_string` SET `entry` = 498,`content_default` = '系统提示：你需要提供一个公会名字!' WHERE `trinity_string`.`entry` = 498;
UPDATE `trinity_string` SET `entry` = 499,`content_default` = '系统提示：玩家没有被找到!' WHERE `trinity_string`.`entry` = 499;
UPDATE `trinity_string` SET `entry` = 500,`content_default` = '系统提示：玩家已经有一个公会!' WHERE `trinity_string`.`entry` = 500;
UPDATE `trinity_string` SET `entry` = 501,`content_default` = '公会没被创建! (是否已经存在?)' WHERE `trinity_string`.`entry` = 501;
UPDATE `trinity_string` SET `entry` = 502,`content_default` = '没有物品从物品库 ''%u'' 里找到.' WHERE `trinity_string`.`entry` = 502;
UPDATE `trinity_string` SET `entry` = 504,`content_default` = '物品 ''%i'' ''%s''  背包 %i' WHERE `trinity_string`.`entry` = 504;
UPDATE `trinity_string` SET `entry` = 505,`content_default` = '物品 ''%i'' 不存在.' WHERE `trinity_string`.`entry` = 505;
UPDATE `trinity_string` SET `entry` = 506,`content_default` = '物品 ''%i'' ''%s'' 已加入背包 %i' WHERE `trinity_string`.`entry` = 506;
UPDATE `trinity_string` SET `entry` = 507,`content_default` = '物品保存失败!' WHERE `trinity_string`.`entry` = 507;
UPDATE `trinity_string` SET `entry` = 545,`content_default` = '*** 是一个销售师!' WHERE `trinity_string`.`entry` = 545;
UPDATE `trinity_string` SET `entry` = 546,`content_default` = '*** 是一个训练师!' WHERE `trinity_string`.`entry` = 546;
UPDATE `trinity_string` SET `entry` = 547,`content_default` = '副本ID: %u' WHERE `trinity_string`.`entry` = 547;
UPDATE `trinity_string` SET `entry` = 548,`content_default` = '玩家%s %s (guid: %u) 帐号: %s (id: %u) G M等级: %u 最后IP: %s 最后登陆: %s Latency: %ums' WHERE `trinity_string`.`entry` = 548;
UPDATE `trinity_string` SET `entry` = 550,`content_default` = '命令提示：命令 .pinfo 不支持  ''rep'' 选择,玩家不在线.' WHERE `trinity_string`.`entry` = 550;
UPDATE `trinity_string` SET `entry` = 551,`content_default` = '%s 探索了所有地区.' WHERE `trinity_string`.`entry` = 551;
UPDATE `trinity_string` SET `entry` = 552,`content_default` = '%s 没有更多的探索区.' WHERE `trinity_string`.`entry` = 552;
UPDATE `trinity_string` SET `entry` = 553,`content_default` = '%s 你探索了所有地带.' WHERE `trinity_string`.`entry` = 553;
UPDATE `trinity_string` SET `entry` = 554,`content_default` = '%s 你掩藏了所有区域.' WHERE `trinity_string`.`entry` = 554;
UPDATE `trinity_string` SET `entry` = 555,`content_default` = '悬停启用' WHERE `trinity_string`.`entry` = 555;
UPDATE `trinity_string` SET `entry` = 556,`content_default` = '悬停关闭' WHERE `trinity_string`.`entry` = 556;
UPDATE `trinity_string` SET `entry` = 560,`content_default` = '该地区已被定为探索.' WHERE `trinity_string`.`entry` = 560;
UPDATE `trinity_string` SET `entry` = 561,`content_default` = '区域被设置了依照没被探索.' WHERE `trinity_string`.`entry` = 561;
UPDATE `trinity_string` SET `entry` = 577,`content_default` = '你现在处于隐身状态.' WHERE `trinity_string`.`entry` = 577;
UPDATE `trinity_string` SET `entry` = 578,`content_default` = '你现在处于可见状态.' WHERE `trinity_string`.`entry` = 578;
UPDATE `trinity_string` SET `entry` = 580,`content_default` = '玩家 %s 学会了所有的本种族本职业的魔法,包括任何奖励的技能.' WHERE `trinity_string`.`entry` = 580;
UPDATE `trinity_string` SET `entry` = 584,`content_default` = '没有事件被找到!' WHERE `trinity_string`.`entry` = 584;
UPDATE `trinity_string` SET `entry` = 585,`content_default` = '事件不存在!' WHERE `trinity_string`.`entry` = 585;
UPDATE `trinity_string` SET `entry` = 586,`content_default` = '事件 %u: %s%s\n开始: %s 结束: %s 发生: %s 全程: %s\n下一次状态改变: %s' WHERE `trinity_string`.`entry` = 586;
UPDATE `trinity_string` SET `entry` = 587,`content_default` = '事件 %u 已经开始!' WHERE `trinity_string`.`entry` = 587;
UPDATE `trinity_string` SET `entry` = 588,`content_default` = '事件 %u 没有开始!' WHERE `trinity_string`.`entry` = 588;
UPDATE `trinity_string` SET `entry` = 600,`content_default` = '联盟获得胜利!' WHERE `trinity_string`.`entry` = 600;
UPDATE `trinity_string` SET `entry` = 601,`content_default` = '部落获得胜利!' WHERE `trinity_string`.`entry` = 601;
UPDATE `trinity_string` SET `entry` = 602,`content_default` = '战场战歌峡谷争夺1分钟倒计时中...' WHERE `trinity_string`.`entry` = 602;
UPDATE `trinity_string` SET `entry` = 603,`content_default` = '战场战歌峡谷争夺，在30秒后开始。大家做好准备!' WHERE `trinity_string`.`entry` = 603;
UPDATE `trinity_string` SET `entry` = 604,`content_default` = '战场战歌峡谷争夺正式开始!' WHERE `trinity_string`.`entry` = 604;
UPDATE `trinity_string` SET `entry` = 605,`content_default` = '$n 夺取了部落旗子!' WHERE `trinity_string`.`entry` = 605;
UPDATE `trinity_string` SET `entry` = 606,`content_default` = '$n 夺取了联盟旗子!' WHERE `trinity_string`.`entry` = 606;
UPDATE `trinity_string` SET `entry` = 607,`content_default` = '部落旗子被 $n 降下!' WHERE `trinity_string`.`entry` = 607;
UPDATE `trinity_string` SET `entry` = 608,`content_default` = '联盟旗子被 $n 降下!' WHERE `trinity_string`.`entry` = 608;
UPDATE `trinity_string` SET `entry` = 609,`content_default` = '联盟旗子被 $n 返回了到它的基地!' WHERE `trinity_string`.`entry` = 609;
UPDATE `trinity_string` SET `entry` = 610,`content_default` = '部落旗子被 $n 返回了到它的基地!' WHERE `trinity_string`.`entry` = 610;
UPDATE `trinity_string` SET `entry` = 611,`content_default` = '部落旗子被 $n 拾起!' WHERE `trinity_string`.`entry` = 611;
UPDATE `trinity_string` SET `entry` = 612,`content_default` = '魔兽世界：联盟旗子被 $n 拾起!' WHERE `trinity_string`.`entry` = 612;
UPDATE `trinity_string` SET `entry` = 613,`content_default` = '旗子现在被安置在他们的基地.' WHERE `trinity_string`.`entry` = 613;
UPDATE `trinity_string` SET `entry` = 614,`content_default` = '联盟旗帜已经被重置' WHERE `trinity_string`.`entry` = 614;
UPDATE `trinity_string` SET `entry` = 615,`content_default` = '联盟旗帜已经被重置!' WHERE `trinity_string`.`entry` = 615;
UPDATE `trinity_string` SET `entry` = 636,`content_default` = '战场暴风之眼争夺1分钟倒计时中....' WHERE `trinity_string`.`entry` = 636;
UPDATE `trinity_string` SET `entry` = 637,`content_default` = '战场暴风之眼争夺，在30秒后开始。大家做好准备!.' WHERE `trinity_string`.`entry` = 637;
UPDATE `trinity_string` SET `entry` = 638,`content_default` = '战场暴风之眼争夺正式开始!!' WHERE `trinity_string`.`entry` = 638;
UPDATE `trinity_string` SET `entry` = 650,`content_default` = '联盟' WHERE `trinity_string`.`entry` = 650;
UPDATE `trinity_string` SET `entry` = 651,`content_default` = '部落' WHERE `trinity_string`.`entry` = 651;
UPDATE `trinity_string` SET `entry` = 657,`content_default` = '此 %s 采取了 %s' WHERE `trinity_string`.`entry` = 657;
UPDATE `trinity_string` SET `entry` = 658,`content_default` = '$n 保卫了  %s' WHERE `trinity_string`.`entry` = 658;
UPDATE `trinity_string` SET `entry` = 659,`content_default` = '$n 攻击了  %s' WHERE `trinity_string`.`entry` = 659;
UPDATE `trinity_string` SET `entry` = 660,`content_default` = '$n 主持这个 %s 吧! 如果听之任之, 这个 %s 将在1 分钟之内控制它!' WHERE `trinity_string`.`entry` = 660;
UPDATE `trinity_string` SET `entry` = 661,`content_default` = '战场阿拉西盆地争夺1分钟倒计时中...' WHERE `trinity_string`.`entry` = 661;
UPDATE `trinity_string` SET `entry` = 662,`content_default` = '战场阿拉西盆地争夺，在30秒后开始。大家做好准备!' WHERE `trinity_string`.`entry` = 662;
UPDATE `trinity_string` SET `entry` = 663,`content_default` = '战场阿拉西盆地争夺正式开始!' WHERE `trinity_string`.`entry` = 663;
UPDATE `trinity_string` SET `entry` = 664,`content_default` = '联盟已收集到$1776W资源, 并已接近胜利!' WHERE `trinity_string`.`entry` = 664;
UPDATE `trinity_string` SET `entry` = 665,`content_default` = '部落已收集到$1777W资源, 并已接近胜利!' WHERE `trinity_string`.`entry` = 665;
UPDATE `trinity_string` SET `entry` = 666,`content_default` = '你在最近的 %s 战斗之后,我们努力想为你颁发一个荣誉标志却没有成功,结束后你会发现这个荣誉标志的,但不是此刻,感谢你在 %s 的战斗.' WHERE `trinity_string`.`entry` = 666;
UPDATE `trinity_string` SET `entry` = 686,`content_default` = '旗子已经被降下!' WHERE `trinity_string`.`entry` = 686;
UPDATE `trinity_string` SET `entry` = 687,`content_default` = '旗帜已经被重置' WHERE `trinity_string`.`entry` = 687;
UPDATE `trinity_string` SET `entry` = 700,`content_default` = '你必须达到等级  %u 才能进入竞技场.' WHERE `trinity_string`.`entry` = 700;
UPDATE `trinity_string` SET `entry` = 701,`content_default` = '一分钟后竞技场争斗开始!' WHERE `trinity_string`.`entry` = 701;
UPDATE `trinity_string` SET `entry` = 702,`content_default` = '三十秒后竞技场争斗开始!' WHERE `trinity_string`.`entry` = 702;
UPDATE `trinity_string` SET `entry` = 703,`content_default` = '十五秒后竞技场争斗开始!' WHERE `trinity_string`.`entry` = 703;
UPDATE `trinity_string` SET `entry` = 704,`content_default` = '竞技场争斗开始了!' WHERE `trinity_string`.`entry` = 704;
UPDATE `trinity_string` SET `entry` = 705,`content_default` = '你必须等待 %s 才能继续喊话.' WHERE `trinity_string`.`entry` = 705;
UPDATE `trinity_string` SET `entry` = 706,`content_default` = '这些道具在装备/存放中出现一个问题.' WHERE `trinity_string`.`entry` = 706;
UPDATE `trinity_string` SET `entry` = 707,`content_default` = '%s 免打扰状态下无法收到悄悄话: %s' WHERE `trinity_string`.`entry` = 707;
UPDATE `trinity_string` SET `entry` = 708,`content_default` = '%s 不在机器旁: %s' WHERE `trinity_string`.`entry` = 708;
UPDATE `trinity_string` SET `entry` = 709,`content_default` = '请勿打扰' WHERE `trinity_string`.`entry` = 709;
UPDATE `trinity_string` SET `entry` = 710,`content_default` = '不在机器旁' WHERE `trinity_string`.`entry` = 710;
UPDATE `trinity_string` SET `entry` = 712,`content_default` = '|cffff0000[战场公告]:|r %s -- [%u-%u] 联盟: 目前%u人 (需: %u人), 部落: 目前%u人 (需: %u人)|r' WHERE `trinity_string`.`entry` = 712;
